// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	profiles "tasquest.com/server/domain/profiles"
)

// ProfileManager is an autogenerated mock type for the ProfileManager type
type ProfileManager struct {
	mock.Mock
}

// createProfile provides a mock function with given fields: command
func (_m *ProfileManager) createProfile(command profiles.CreateUserProfile) (profiles.Profile, error) {
	ret := _m.Called(command)

	var r0 profiles.Profile
	if rf, ok := ret.Get(0).(func(profiles.CreateUserProfile) profiles.Profile); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(profiles.Profile)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(profiles.CreateUserProfile) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
