// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"tasquest.com/server/gamification/adventurers"
)

// ProfileManager is an autogenerated mock type for the ProfileManager type
type ProfileManager struct {
	mock.Mock
}

// createProfile provides a mock function with given fields: command
func (_m *ProfileManager) createProfile(command adventurers.CreateAdventurer) (adventurers.Adventurer, error) {
	ret := _m.Called(command)

	var r0 adventurers.Adventurer
	if rf, ok := ret.Get(0).(func(adventurers.CreateAdventurer) adventurers.Adventurer); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(adventurers.Adventurer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(adventurers.CreateAdventurer) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
