// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	leveling "tasquest.com/server/application/gamification/leveling"
	commons "tasquest.com/server/commons"

	uuid "github.com/google/uuid"
)

// ProgressionFinder is an autogenerated mock type for the ProgressionFinder type
type ProgressionFinder struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *ProgressionFinder) FindByID(id uuid.UUID) (leveling.ExpLevel, error) {
	ret := _m.Called(id)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(uuid.UUID) leveling.ExpLevel); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLatestLevel provides a mock function with given fields:
func (_m *ProgressionFinder) FindLatestLevel() (leveling.ExpLevel, error) {
	ret := _m.Called()

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func() leveling.ExpLevel); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLevelForExperience provides a mock function with given fields: experience
func (_m *ProgressionFinder) FindLevelForExperience(experience int64) (leveling.ExpLevel, error) {
	ret := _m.Called(experience)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(int64) leveling.ExpLevel); ok {
		r0 = rf(experience)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(experience)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLevelInformation provides a mock function with given fields: level
func (_m *ProgressionFinder) FindLevelInformation(level int) (leveling.ExpLevel, error) {
	ret := _m.Called(level)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(int) leveling.ExpLevel); ok {
		r0 = rf(level)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(level)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneByFilter provides a mock function with given fields: filter
func (_m *ProgressionFinder) FindOneByFilter(filter commons.SqlFilter) (leveling.ExpLevel, error) {
	ret := _m.Called(filter)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(commons.SqlFilter) leveling.ExpLevel); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(commons.SqlFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
