// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	leveling "tasquest.com/server/application/gamification/leveling"
)

// ProgressionFinder is an autogenerated mock type for the ProgressionFinder type
type ProgressionFinder struct {
	mock.Mock
}

// FindLevelByExperience provides a mock function with given fields: experience
func (_m *ProgressionFinder) FindLevelByExperience(experience int64) (leveling.ExpLevel, error) {
	ret := _m.Called(experience)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(int64) leveling.ExpLevel); ok {
		r0 = rf(experience)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(experience)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLevelInformation provides a mock function with given fields: level
func (_m *ProgressionFinder) FindLevelInformation(level int) (leveling.ExpLevel, error) {
	ret := _m.Called(level)

	var r0 leveling.ExpLevel
	if rf, ok := ret.Get(0).(func(int) leveling.ExpLevel); ok {
		r0 = rf(level)
	} else {
		r0 = ret.Get(0).(leveling.ExpLevel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(level)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
