// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	security "tasquest.com/server/application/security"
)

// UserPersistence is an autogenerated mock type for the UserPersistence type
type UserPersistence struct {
	mock.Mock
}

// Save provides a mock function with given fields: user
func (_m *UserPersistence) Save(user security.User) (security.User, error) {
	ret := _m.Called(user)

	var r0 security.User
	if rf, ok := ret.Get(0).(func(security.User) security.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(security.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(security.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
