// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
	"go.mongodb.org/mongo-driver/mongo"
	"tasquest.com/server/adapters/input/rest"
	"tasquest.com/server/adapters/output/databases/mongorepositories"
	"tasquest.com/server/adapters/output/eventbus/message-bus"
	"tasquest.com/server/application/gamification/adventurers"
	"tasquest.com/server/application/gamification/leveling"
	"tasquest.com/server/application/gamification/tasks"
	"tasquest.com/server/application/security"
	"tasquest.com/server/commons"
	"tasquest.com/server/infra/events"
	"tasquest.com/server/infra/web"
)

// Injectors from init_instances.go:

/**************************
 *    Common Providers    *
 **************************/
func loggerWire() *logrus.Logger {
	logger := commons.ProvideLogger()
	return logger
}

/**************************
 *    Infra Providers     *
 **************************/
func databaseWire() *mongo.Database {
	database := mongorepositories.ProvideDatasource()
	return database
}

func webServerWire() *gin.Engine {
	engine := web.ProvideWebServer()
	return engine
}

func eventPublisherWire() events.Publisher {
	messenger := message_bus.NewMessenger()
	return messenger
}

func eventSubscriberWire() events.Subscriber {
	messenger := message_bus.NewMessenger()
	return messenger
}

/**************************
 *    security Providers  *
 **************************/
func userFinderWire() security.UserFinder {
	database := databaseWire()
	userRepository := mongorepositories.NewUserRepository(database)
	return userRepository
}

func userPersistenceWire() security.UserPersistence {
	database := databaseWire()
	userRepository := mongorepositories.NewUserRepository(database)
	return userRepository
}

func userServiceWire() security.UserService {
	userFinder := userFinderWire()
	userPersistence := userPersistenceWire()
	userManagement := security.NewUserManagement(userFinder, userPersistence)
	return userManagement
}

/*****************************
 *    Adventurers Providers  *
 *****************************/
func adventurerFinderWire() adventurers.AdventurerFinder {
	database := databaseWire()
	adventurerRepository := mongorepositories.NewAdventurerRepository(database)
	return adventurerRepository
}

func adventurerPersistenceWire() adventurers.AdventurerPersistence {
	database := databaseWire()
	adventurerRepository := mongorepositories.NewAdventurerRepository(database)
	return adventurerRepository
}

func adventurerServiceWire() adventurers.AdventurerService {
	adventurerFinder := adventurerFinderWire()
	adventurerPersistence := adventurerPersistenceWire()
	userService := userServiceWire()
	adventurerManager := adventurers.NewAdventurerManager(adventurerFinder, adventurerPersistence, userService)
	return adventurerManager
}

/*****************************
 *      Task Providers       *
 *****************************/
func taskFinderWire() tasks.TaskFinder {
	database := databaseWire()
	taskRepository := mongorepositories.NewTaskRepository(database)
	return taskRepository
}

func taskPersistenceWire() tasks.TaskPersistence {
	database := databaseWire()
	taskRepository := mongorepositories.NewTaskRepository(database)
	return taskRepository
}

func taskServiceWire() tasks.TaskService {
	taskFinder := taskFinderWire()
	taskPersistence := taskPersistenceWire()
	adventurerFinder := adventurerFinderWire()
	taskManager := tasks.NewTaskManager(taskFinder, taskPersistence, adventurerFinder)
	return taskManager
}

func progressionFinderWire() leveling.ProgressionFinder {
	database := databaseWire()
	progressionRepository := mongorepositories.NewProgressionRepository(database)
	return progressionRepository
}

func progressionPersistenceWire() leveling.ProgressionPersistence {
	database := databaseWire()
	progressionRepository := mongorepositories.NewProgressionRepository(database)
	return progressionRepository
}

func progressionServiceWire() leveling.ProgressionService {
	progressionFinder := progressionFinderWire()
	progressionPersistence := progressionPersistenceWire()
	adventurerService := adventurerServiceWire()
	adventurerFinder := adventurerFinderWire()
	publisher := eventPublisherWire()
	progressionManagement := leveling.NewProgressionManagement(progressionFinder, progressionPersistence, adventurerService, adventurerFinder, publisher)
	return progressionManagement
}

/**************************
 *    Api Providers  *
 **************************/
func authApiWireBuilder() *rest.AuthAPI {
	engine := web.ProvideWebServer()
	userService := userServiceWire()
	logger := commons.ProvideLogger()
	errorHandler := commons.ProvideErrorHandler(logger)
	authAPI := rest.NewAuthApi(engine, userService, errorHandler)
	return authAPI
}

// init_instances.go:

func Bootstrap() {

	loggerWire()

	databaseWire()
	webServerWire()
	eventPublisherWire()
	eventSubscriberWire()

	userPersistenceWire()
	userFinderWire()
	userServiceWire()

	adventurerFinderWire()
	adventurerPersistenceWire()
	adventurerServiceWire()

	taskFinderWire()
	taskPersistenceWire()
	taskServiceWire()

	progressionFinderWire()
	progressionPersistenceWire()
	progressionServiceWire()

	authApiWireBuilder()
}
