// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"tasquest-server/src/api/v1"
	"tasquest-server/src/common/errorhandler"
	"tasquest-server/src/common/logs"
	"tasquest-server/src/infra/database"
	"tasquest-server/src/infra/web"
	"tasquest-server/src/security"
	"tasquest-server/src/security/dao"
)

// Injectors from init_apis.go:

func InitAuthApi() *v1.AuthAPI {
	engine := web.ProvideWebserver()
	client := database.ProvideDatasource()
	userRepository := dao.ProvideUserRepository(client)
	securitySecurity := security.ProvideSecurity(userRepository)
	logger := logs.ProvideLogger()
	errorHandler := errorhandler.ProvideErrorHandler(logger)
	authAPI := v1.ProvideAuthAPI(engine, securitySecurity, errorHandler)
	return authAPI
}
